---
- name: Install memcached
  apt: 
    name: memcached
    state: present
  notify:
    - enable memcached

- name: Setup configuration
  template:
    src: memcached.conf.j2
    dest: /etc/memcached.conf
  notify:
   - restart memcached

- name: create systemd directory for override memcached value
  file:
    state: directory
    path: /etc/systemd/system/memcached.service.d

- name: increase number of openfiles and process limits
  copy:
    src: systemd_override.conf
    dest: /etc/systemd/system/memcached.service.d/override.conf
  notify:
    - restart memcached
