---

- name: restart memcached
  service:
    name: memcached
    state: restarted

- name: enable memcached
  service: 
    name: memcached
    enabled: yes

- name: start memcached
  service: 
    name: memcached
    daemon_reload: yes
    enabled: yes
